refactor: $TSFixMe修正
shngmsw/ikabu pull request #602
Opened 2023-06-18 21:53 UTC by root-lump

DB移行必須
チャンネル管理系、TeamDivider系はやっつけ対処みたいな箇所あり

2023-06-19 06:10 UTC, root-lump commented
マイグレーションデプロイ後に移行

### 移行が必要なテーブル
```
friend_code -> friend_code
message_count -> message_count
reactions -> user_reaction
total_reactions -> reaction
```
### できれば移行したいテーブル
```
members -> member
```

2023-06-19 07:37 UTC, root-lump commented on src/app/logs/modals/recruit_modal_log.ts
> +            commandLog = commandLog + subcomponents.components[0].customId + ': ' + subcomponents.components[0].value + '\n';
```Typescript
export interface BaseModalData {
  customId: string;
  type: ComponentType;
}

export interface TextInputModalData extends BaseModalData {
  type: ComponentType.TextInput;
  value: string;
}

export interface ActionRowModalData {
  type: ComponentType.ActionRow;
  components: ModalData[];
}

export type ModalData = TextInputModalData | ActionRowModalData;

export class ModalSubmitFields {
  constructor(components: ModalActionRowComponent[][]);
  public components: ActionRow<ModalActionRowComponent>;
  public fields: Collection<string, ModalActionRowComponent>;
  public getField<T extends ComponentType>(customId: string, type: T): { type: T } & ModalData;
  public getField(customId: string, type?: ComponentType): ModalData;
  public getTextInputValue(customId: string): string;
}
```
ModalDataがActionRowModalDataだけで回る可能性があって判別できてなかったのでtypeで判定かけたら問題なく動きました。

2023-06-21 16:20 UTC, shngmsw requested changes

2023-06-21 16:36 UTC, root-lump commented on src/db/participant_service.ts
> +};
https://github.com/shngmsw/ikabu/pull/602/commits/1048c0b52187e2e4e2931dcc46270c895b170e19 アッパーキャメルに修正

2023-06-21 16:38 UTC, root-lump commented on src/app/feat-recruit/interactions/commands/anarchy_recruit.ts
一応前にボタンの処理書いたときに
募集者: `recruiter`
募集時参加確定者: `attendee`
参加希望者: `applicant`
と命名したのでそれに合わせた感じ
まだ気づいてない場所は多々あると思うから適宜直してく感じかな

2023-06-21 16:43 UTC, root-lump commented on src/app/feat-recruit/interactions/modals/fes_recruit_modal.ts
> +        const hostMention = `<@${recruiter.userId}>`;
一応
Discord APIから拾ってきた*GuildMember* : `member`
Discord APIから拾ってきた募集主の*GuildMember* : `hostMember`
それから拾ってきたプロパティ: `host〇〇`

DBから拾ってきた募集主の*Member* : `recruiter`
のつもり…

DBから拾ってきたものだけのとこは*Member*でも`member`ってつけてるとこもある

2023-06-21 16:44 UTC, root-lump commented on src/app/feat-utils/other/omikuji.ts
>  }
おみくじって廃止されてたんですか？
普通に残してても良さそうだけど

2023-06-22 01:31 UTC, shngmsw commented on src/app/feat-utils/other/omikuji.ts
>  }
スラコマ化するときにめんどくさっていって削除したんだと思われる
https://github.com/shngmsw/ikabu/commit/eeb6b78872b8754a628b8a97ea95cdbe317d5752

復活させてもいいけど、リニューアルしたいから別のPRかな

2023-06-22 01:34 UTC, shngmsw approved these changes
![LGTM](https://img.shields.io/badge/good-LGTM-green.svg)

2023-06-24 16:47 UTC, merged