スケジュールイベントを自動作成、ステージ情報をnode-cronで実行
shngmsw/ikabu pull request #614
Opened 2023-07-08 10:37 UTC by shngmsw

- node-cronで奇数時間に実行するjobを定義
- イベントマッチのスケジュールをsplatoon3.inkから取得し、まだ追加されてなければスケジュールイベントを作成
- ステージ情報を取得し、旧stageinfoコマンドを定期実行するように変更
   - .envに `CHANNEL_ID_STAGE_INFO` 追加

2023-07-08 10:38 UTC, shngmsw commented on tsconfig.json
> +    "target": "es2021",
repalceAll使いたかったので変更

2023-07-09 10:36 UTC, root-lump requested changes

2023-07-09 11:07 UTC, shngmsw commented on src/app/handlers/message_handler.ts
> -
[ce2b418](https://github.com/shngmsw/ikabu/pull/614/commits/ce2b4186d974123a9a6027c37c512f0c34dcaee4)
対応しました

2023-07-09 11:08 UTC, shngmsw commented on src/app/feat-utils/splat3/stageinfo.ts
> +            await stageInfoChannel.send(`スケジュールデータを取得できなかったでし！\n${new Date().toLocaleString()}`);
対応しました

2023-07-09 11:15 UTC, shngmsw commented on src/app/common/manager/guild_scheduled_event_manager.ts
他のファイル名と合わせた長さにすることよりも、わかりやすさを優先する意図です。
guild_eventだとdiscordjsの`guildMemberAddEvent`などのeventとも捉えられるので、scheduled_eventにしました。
[DiscordAPIの正式名称](https://discord.com/developers/docs/resources/guild-scheduled-event)から取ってます

2023-07-09 11:16 UTC, shngmsw commented on src/app/common/manager/guild_scheduled_event_manager.ts
> +export async function subscribeSplatEventMatch(guild: Guild) {
対応ついでにstageinfoも移動しました。
[d8f1291](https://github.com/shngmsw/ikabu/pull/614/commits/d8f1291678bdeee050665af78fea7457207e3e11)

2023-07-09 11:16 UTC, shngmsw commented on src/app/index.ts
> +    console.log('cron job finished');
対応しました
[f85b23](https://github.com/shngmsw/ikabu/pull/614/commits/f85b23a63648e8f20edeb92a71138d2894f39d7c)

2023-07-09 11:18 UTC, shngmsw commented on src/app/common/manager/guild_scheduled_event_manager.ts
> +            const eventNameWithTime = `${name} ${startTime.toLocaleString()}`;
これも対応済み

2023-07-09 11:18 UTC, shngmsw commented on tsconfig.json
> +    "target": "es2021",
やるにしても別のPRでやります！

2023-07-09 11:20 UTC, root-lump requested changes

2023-07-09 11:20 UTC, root-lump commented on src/app/handlers/message_handler.ts
> +                const member = await guild.members.fetch(message.author.id);
![should](https://img.shields.io/badge/review-should-important.svg)
再度お手数をおかけしますが、searchAPIMember使用するように変えといてもらってもいいですか？

2023-07-09 11:26 UTC, root-lump commented on src/app/common/manager/guild_scheduled_event_manager.ts
なるほど！
それなら、managerの各関数名もそちらに合わせてほしいです！
`creteGuildScheduledEvent(...)`的な

2023-07-09 11:27 UTC, shngmsw commented on src/app/handlers/message_handler.ts
> +                const member = await guild.members.fetch(message.author.id);
対応済み～
[0695b0a](https://github.com/shngmsw/ikabu/pull/614/commits/0695b0ae6b56fd32be7b69aae91ac9e55f082e3e)

2023-07-09 11:31 UTC, shngmsw commented on src/app/common/manager/guild_scheduled_event_manager.ts
ほい！
[6541dc4](https://github.com/shngmsw/ikabu/pull/614/commits/6541dc460db3e4acee90b91a3f150a2d585742e0)

2023-07-09 11:33 UTC, root-lump approved these changes
お疲れ様でした。

2023-07-09 11:34 UTC, merged